/**
 * A dialog component for saving and creating themes with compact color picker.
 * Built using ShadCN UI Dialog and Sheet components.
 * Generated by our Platform itself
 */
import { experimental_useObject as useObject } from '@ai-sdk/react';
import useSWR from 'swr';
import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogOverlay,
  DialogTitle,
  DialogHeader,
  DialogDescription,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { useState, useEffect, FormEvent } from "react";
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
  SheetDescription,
  SheetFooter,
} from "@/components/ui/sheet";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ChevronDown, ExternalLink, Loader2} from "lucide-react"

import { getApiKey, getSelectedModel, getLocalSavedTheme } from "@/lib/utils";
import { SavedTheme, themeSchema } from "@/lib/types";
import { toast } from "sonner";
import { getSavedTheme } from '@/lib/fetchers';

/**
 * Dialog component for managing saved themes and creating new themes
 * Handles theme selection, creation, and persistence to localStorage
 */
export function ThemeDialog({ savedThemes}: {savedThemes: SavedTheme[]}) {
  // State management for dialog and sheet visibility
  const [open, setOpen] = useState(false); // Controls main dialog open/close state
  const [selectedTheme, setSelectedTheme] = useState<SavedTheme | null>(null); // Tracks currently selected theme
  const [sheetOpen, setSheetOpen] = useState(false); // Controls theme creation sheet open/close state
  
  // AI object hook for theme creation with validation
  const { submit, isLoading } = useObject({
    api: '/api/theme',
    schema: themeSchema,
    onFinish({object}){
      if(!object) return;
      const newGeneratedTheme: SavedTheme = {
        id: crypto.randomUUID(),
        name:object.name,
        color:object.color,
        data:object.data,
        createdAt: new Date()
      }
      savedThemes.unshift(newGeneratedTheme)
     setSheetOpen(false)
    },
    onError(){
     toast.error("Not enough API credits left.",{
          position: "top-center"
      })
    }
  });

  /**
   * Handles theme creation form submission
   * Validates model selection and API key before submitting
   * @param e - Form event from theme creation form
   */
  const handleSaveTheme = (e: FormEvent<HTMLFormElement>) => {
    // Prevent default form submission to avoid triggering parent form
    e.preventDefault();
    e.stopPropagation();
    
    // Validate selected model exists
    const selectedModel = getSelectedModel()
    if(!selectedModel){
      return toast.error("Please select the model",{
        position:"top-center"
      })
    }
    
    // Validate API key is available for selected model
    const isSelectedModelAPIKeyAvail = getApiKey(selectedModel?.llm)
    if(!isSelectedModelAPIKeyAvail){
      return toast.error(`Please add the API key for ${selectedModel.llm}`,{
        position:"top-center"
      })
    }
    
    // Extract form data and validate theme content
    const form = e.currentTarget;
    const formData = new FormData(form);
    const themeData = formData.get('themeData') as string;

    if (!themeData.trim()) {
      alert('Theme cannot be empty.');
      return;
    }

    // Submit theme data to AI for processing
    submit({llm: selectedModel.llm, apiKey: isSelectedModelAPIKeyAvail, content: themeData})
  }

  /**
   * Load previously selected theme from localStorage on component mount
   * Ensures user's theme preference persists across sessions
   */
  useEffect(() => {
    const savedTheme = getLocalSavedTheme()
    if (savedTheme) {
      setSelectedTheme(savedTheme);
    }
  }, []);

  /**
   * Handles theme selection and persists choice to localStorage
   * @param theme - The selected theme object
   */
  const handleThemeSelect = (theme: SavedTheme) => {
    setSelectedTheme(theme);
    // Persist selected theme to localStorage for future sessions
    localStorage.setItem("selectedTheme", JSON.stringify(theme));
  };

  /**
   * Opens the theme creation sheet
   */
  const handleCreateTheme = () => {
    setSheetOpen(true);
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      {/* Dialog trigger button with theme label and dropdown icon */}
      <DialogTrigger asChild>
        <Button variant="ghost" className="font-light text-xs">
          Theme 
          <ChevronDown/>
        </Button>
      </DialogTrigger>
      
      <DialogOverlay />
      
      {/* Main dialog content for theme selection */}
      <DialogContent className="px-4 pt-7 pb-10 ">
        <DialogHeader>
          <DialogTitle className='text-left'>Select Theme</DialogTitle>
          <DialogDescription className='text-left'>
            Choose from your saved themes or create a new one.
          </DialogDescription>
        </DialogHeader>
        
        {/* Header with create theme button */}
        <div className="flex justify-between items-center mb-4">
          <Button variant="link" size="sm" onClick={handleCreateTheme} className="ml-auto font-light">
            Create Theme
          </Button>
        </div>
        
        {/* Grid layout for displaying available themes */}
        <div className="grid grid-cols-2 gap-4 md:grid-cols-3 ">
          {savedThemes.map((theme) => (
            <Button
              key={theme.id}
              variant="outline"
              size="lg"
              className="flex items-center justify-start"
              // Highlight selected theme with colored border
              style={{ border: selectedTheme?.id === theme.id ? `2px solid ${theme.color}`: "" }}
              onClick={() => handleThemeSelect(theme)}
            >
              {/* Color indicator circle */}
              <span
                className="inline-block w-4 h-4 border-none rounded-full mr-0.5 "
                style={{ backgroundColor: theme.color }}
              />
              <span className='hidden md:block'>{theme.name.substring(0, 9)}</span>
              <span className='block md:hidden'>{theme.name.split(" ")[0]}</span>
            </Button>
          ))}
        </div>
      </DialogContent>

      {/* Side sheet for creating new themes */}
      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        <SheetContent side="right" className="p-4">
          <SheetHeader>
            <SheetTitle>Create New Theme</SheetTitle>
            {/* External link to style guide */}
            <SheetDescription>
              <a 
                href="https://www.styleglide.ai/themes" 
                target="_blank" 
                className="text-xs font-medium hover:underline text-blue-400 cursor-pointer flex flex-row items-center gap-2"
              >
                StyleGuide <ExternalLink width={14}/>
              </a>
            </SheetDescription>
          </SheetHeader>
          
          {/* Theme creation form - isolated to prevent parent form interference */}
          <form 
            onSubmit={handleSaveTheme}
            className="space-y-3 px-4"
            // Additional event handlers to prevent form bubbling
            onKeyDown={(e) => {
              // Prevent Enter key from triggering parent form
              if (e.key === 'Enter' && e.ctrlKey) {
                e.preventDefault();
                e.stopPropagation();
                handleSaveTheme(e);
              }
            }}
          >
            <Label htmlFor="theme-data">Theme</Label>
            {/* Large textarea for CSS theme input */}
            <Textarea
              id="theme"
              name="themeData"
              placeholder={themePlaceholder}
              rows={4}
              className="overflow-auto h-[25rem] max-h-[25rem]"
              required
            />
            
            {/* Form submission footer */}
            <SheetFooter className="">
              <Button 
                type="submit" 
                disabled={isLoading}
                // Prevent any potential event bubbling on button click
                onClick={(e) => e.stopPropagation()}
              >
                {isLoading && (<Loader2 className='animate-spin'/>)} 
                Verify theme
              </Button>
            </SheetFooter>
          </form>
        </SheetContent>
      </Sheet>
    </Dialog>
  )
}

/**
 * Main wrapper component that provides data fetching and state management
 * for the ThemeDialog component. Uses SWR for efficient data fetching and caching.
 */
function UserTheme() {
  // SWR hook for fetching saved themes with automatic revalidation
  const {data} = useSWR<SavedTheme[]>("/api/theme", getSavedTheme)

  return (
    <div className="">
      {/* Pass fetched themes and reload function to dialog component */}
      <ThemeDialog savedThemes={data || []}/>
    </div>
  )
}


const themePlaceholder = `
:root {
  --base-50: oklch(0.9843 0.0031 253.87);
  --base-100: oklch(0.972 0.0062 255.47);
  --base-200: oklch(0.9287 0.0087 255.87);
  --base-300: oklch(0.8699 0.0099 256.06);
  --base-400: oklch(0.7049 0.0112 258.31);
  --base-500: oklch(0.5529 0.0121 259.08);
  --base-600: oklch(0.4459 0.0118 257.79);
  --base-700: oklch(0.3722 0.0109 258.11);
  --base-800: oklch(0.2786 0.0093 258.97);
  --base-900: oklch(0.2087 0.0087 261.4);
  --base-950: oklch(0.1293 0.0081 261.69);
  --base-1000: oklch(0.078 0.0074 261.25);

  --primary-50: oklch(0.9645 0.0106 283.77);
  --primary-100: oklch(0.9359 0.0197 284.44);
  --primary-200: oklch(0.8821 0.0382 284.32);
  --primary-300: oklch(0.7984 0.071 284.79);
  --primary-400: oklch(0.6882 0.1148 285.81);
  --primary-500: oklch(0.5961 0.1523 285.45);
  --primary-600: oklch(0.5436 0.1712 285.54);
  --primary-700: oklch(0.4751 0.161 285.34);
  --primary-800: oklch(0.416 0.1351 285.59);
  --primary-900: oklch(0.37 0.1057 286.74);
  --primary-950: oklch(0.2707 0.0738 286.53);
  --primary-1000: oklch(0.2063 0.0531 286.39);

  --secondary-50: oklch(0.9814 0.0123 175.92);
  --secondary-100: oklch(0.9511 0.0388 174.96);
  --secondary-200: oklch(0.9077 0.0715 175.07);
  --secondary-300: oklch(0.8511 0.0818 175.78);
  --secondary-400: oklch(0.7727 0.092 175.76);
  --secondary-500: oklch(0.7011 0.0996 175.92);
  --secondary-600: oklch(0.5985 0.0959 177.64);
  --secondary-700: oklch(0.5099 0.078 179.56);
  --secondary-800: oklch(0.4354 0.0632 181.21);
  --secondary-900: oklch(0.39 0.0511 182.01);
  --secondary-950: oklch(0.2721 0.036 184.95);
  --secondary-1000: oklch(0.1998 0.0262 185.85);

  --background: var(--base-50);
  --foreground: var(--base-800);
  --card: var(--color-white);
  --card-foreground: var(--base-800);
  --popover: var(--color-white);
  --popover-foreground: var(--base-800);
  --primary: var(--primary-600);
  --primary-foreground: var(--color-white);
  --secondary: var(--secondary-900);
  --secondary-foreground: var(--color-white);
  --muted: var(--base-100);
  --muted-foreground: var(--base-600);
  --accent: var(--base-100);
  --accent-foreground: var(--base-800);
  --destructive: oklch(0.577 0.245 27.325);
  --border: var(--base-200);
  --input: var(--base-300);
  --ring: var(--primary-600);
  --chart-1: var(--primary-600);
  --chart-2: var(--secondary-900);
  --chart-3: var(--primary-300);
  --chart-4: var(--secondary-300);
  --chart-5: var(--primary-100);
  --radius: 1rem;
  --sidebar: var(--color-white);
  --sidebar-foreground: var(--base-800);
  --sidebar-primary: var(--primary-600);
  --sidebar-primary-foreground: var(--color-white);
  --sidebar-accent: var(--base-50);
  --sidebar-accent-foreground: var(--base-800);
  --sidebar-border: var(--base-200);
  --sidebar-ring: var(--primary-600);
}

.dark {
  --background: var(--base-950);
  --foreground: var(--base-200);
  --card: var(--base-900);
  --card-foreground: var(--base-200);
  --popover: var(--base-900);
  --popover-foreground: var(--base-200);
  --primary: var(--primary-600);
  --primary-foreground: var(--color-white);
  --secondary: var(--secondary-900);
  --secondary-foreground: var(--color-white);
  --muted: var(--base-800);
  --muted-foreground: var(--base-300);
  --accent: var(--base-800);
  --accent-foreground: var(--base-200);
  --destructive: oklch(0.704 0.191 22.216);
  --border: var(--base-800);
  --input: var(--base-700);
  --ring: var(--primary-600);
  --chart-1: var(--primary-600);
  --chart-2: var(--secondary-900);
  --chart-3: var(--primary-300);
  --chart-4: var(--secondary-300);
  --chart-5: var(--primary-100);
  --sidebar: var(--base-900);
  --sidebar-foreground: var(--base-200);
  --sidebar-primary: var(--primary-600);
  --sidebar-primary-foreground: var(--color-white);
  --sidebar-accent: var(--base-800);
  --sidebar-accent-foreground: var(--base-200);
  --sidebar-border: var(--base-800);
  --sidebar-ring: var(--primary-600);
}
}
`

export default UserTheme